services:
  tierra:
    build: .
    container_name: tierra-app
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3002
