/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as FinancesIndexRouteImport } from './routes/finances/index'
import { Route as DirectoryIndexRouteImport } from './routes/directory/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as CheckinTokenRouteImport } from './routes/checkin/$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DirectoryMinistriesIndexRouteImport } from './routes/directory/ministries/index'
import { Route as DirectoryMembersIndexRouteImport } from './routes/directory/members/index'
import { Route as DirectoryCellGroupsIndexRouteImport } from './routes/directory/cell-groups/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminMembersIndexRouteImport } from './routes/admin/members/index'
import { Route as AdminAttendanceIndexRouteImport } from './routes/admin/attendance/index'
import { Route as DirectoryMinistriesMinistryIdRouteImport } from './routes/directory/ministries/$ministryId'
import { Route as DirectoryMembersMemberIdRouteImport } from './routes/directory/members/$memberId'
import { Route as DirectoryCellGroupsGroupIdRouteImport } from './routes/directory/cell-groups/$groupId'
import { Route as AdminMinistriesMinistryIdRouteImport } from './routes/admin/ministries/$ministryId'
import { Route as AdminMembersNewRouteImport } from './routes/admin/members/new'
import { Route as AdminInventoryRequestsRouteImport } from './routes/admin/inventory/requests'
import { Route as AdminInventoryItemIdRouteImport } from './routes/admin/inventory/$itemId'
import { Route as AdminCellGroupsGroupIdRouteImport } from './routes/admin/cell-groups/$groupId'
import { Route as AdminAttendanceAnalyticsRouteImport } from './routes/admin/attendance/analytics'
import { Route as AdminAttendanceSessionIdRouteImport } from './routes/admin/attendance/$sessionId'
import { Route as AdminMembersMemberIdEditRouteImport } from './routes/admin/members/$memberId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesIndexRoute = FinancesIndexRouteImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinTokenRoute = CheckinTokenRouteImport.update({
  id: '/checkin/$token',
  path: '/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryMinistriesIndexRoute =
  DirectoryMinistriesIndexRouteImport.update({
    id: '/directory/ministries/',
    path: '/directory/ministries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DirectoryMembersIndexRoute = DirectoryMembersIndexRouteImport.update({
  id: '/directory/members/',
  path: '/directory/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryCellGroupsIndexRoute =
  DirectoryCellGroupsIndexRouteImport.update({
    id: '/directory/cell-groups/',
    path: '/directory/cell-groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersIndexRoute = AdminMembersIndexRouteImport.update({
  id: '/admin/members/',
  path: '/admin/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceIndexRoute = AdminAttendanceIndexRouteImport.update({
  id: '/admin/attendance/',
  path: '/admin/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryMinistriesMinistryIdRoute =
  DirectoryMinistriesMinistryIdRouteImport.update({
    id: '/directory/ministries/$ministryId',
    path: '/directory/ministries/$ministryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DirectoryMembersMemberIdRoute =
  DirectoryMembersMemberIdRouteImport.update({
    id: '/directory/members/$memberId',
    path: '/directory/members/$memberId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DirectoryCellGroupsGroupIdRoute =
  DirectoryCellGroupsGroupIdRouteImport.update({
    id: '/directory/cell-groups/$groupId',
    path: '/directory/cell-groups/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMinistriesMinistryIdRoute =
  AdminMinistriesMinistryIdRouteImport.update({
    id: '/admin/ministries/$ministryId',
    path: '/admin/ministries/$ministryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMembersNewRoute = AdminMembersNewRouteImport.update({
  id: '/admin/members/new',
  path: '/admin/members/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRequestsRoute = AdminInventoryRequestsRouteImport.update({
  id: '/admin/inventory/requests',
  path: '/admin/inventory/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryItemIdRoute = AdminInventoryItemIdRouteImport.update({
  id: '/admin/inventory/$itemId',
  path: '/admin/inventory/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCellGroupsGroupIdRoute = AdminCellGroupsGroupIdRouteImport.update({
  id: '/admin/cell-groups/$groupId',
  path: '/admin/cell-groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceAnalyticsRoute =
  AdminAttendanceAnalyticsRouteImport.update({
    id: '/admin/attendance/analytics',
    path: '/admin/attendance/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAttendanceSessionIdRoute =
  AdminAttendanceSessionIdRouteImport.update({
    id: '/admin/attendance/$sessionId',
    path: '/admin/attendance/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMembersMemberIdEditRoute =
  AdminMembersMemberIdEditRouteImport.update({
    id: '/admin/members/$memberId/edit',
    path: '/admin/members/$memberId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/attendance/$sessionId': typeof AdminAttendanceSessionIdRoute
  '/admin/attendance/analytics': typeof AdminAttendanceAnalyticsRoute
  '/admin/cell-groups/$groupId': typeof AdminCellGroupsGroupIdRoute
  '/admin/inventory/$itemId': typeof AdminInventoryItemIdRoute
  '/admin/inventory/requests': typeof AdminInventoryRequestsRoute
  '/admin/members/new': typeof AdminMembersNewRoute
  '/admin/ministries/$ministryId': typeof AdminMinistriesMinistryIdRoute
  '/directory/cell-groups/$groupId': typeof DirectoryCellGroupsGroupIdRoute
  '/directory/members/$memberId': typeof DirectoryMembersMemberIdRoute
  '/directory/ministries/$ministryId': typeof DirectoryMinistriesMinistryIdRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/members': typeof AdminMembersIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/directory/cell-groups': typeof DirectoryCellGroupsIndexRoute
  '/directory/members': typeof DirectoryMembersIndexRoute
  '/directory/ministries': typeof DirectoryMinistriesIndexRoute
  '/admin/members/$memberId/edit': typeof AdminMembersMemberIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/attendance/$sessionId': typeof AdminAttendanceSessionIdRoute
  '/admin/attendance/analytics': typeof AdminAttendanceAnalyticsRoute
  '/admin/cell-groups/$groupId': typeof AdminCellGroupsGroupIdRoute
  '/admin/inventory/$itemId': typeof AdminInventoryItemIdRoute
  '/admin/inventory/requests': typeof AdminInventoryRequestsRoute
  '/admin/members/new': typeof AdminMembersNewRoute
  '/admin/ministries/$ministryId': typeof AdminMinistriesMinistryIdRoute
  '/directory/cell-groups/$groupId': typeof DirectoryCellGroupsGroupIdRoute
  '/directory/members/$memberId': typeof DirectoryMembersMemberIdRoute
  '/directory/ministries/$ministryId': typeof DirectoryMinistriesMinistryIdRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/members': typeof AdminMembersIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/directory/cell-groups': typeof DirectoryCellGroupsIndexRoute
  '/directory/members': typeof DirectoryMembersIndexRoute
  '/directory/ministries': typeof DirectoryMinistriesIndexRoute
  '/admin/members/$memberId/edit': typeof AdminMembersMemberIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/finances/': typeof FinancesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/attendance/$sessionId': typeof AdminAttendanceSessionIdRoute
  '/admin/attendance/analytics': typeof AdminAttendanceAnalyticsRoute
  '/admin/cell-groups/$groupId': typeof AdminCellGroupsGroupIdRoute
  '/admin/inventory/$itemId': typeof AdminInventoryItemIdRoute
  '/admin/inventory/requests': typeof AdminInventoryRequestsRoute
  '/admin/members/new': typeof AdminMembersNewRoute
  '/admin/ministries/$ministryId': typeof AdminMinistriesMinistryIdRoute
  '/directory/cell-groups/$groupId': typeof DirectoryCellGroupsGroupIdRoute
  '/directory/members/$memberId': typeof DirectoryMembersMemberIdRoute
  '/directory/ministries/$ministryId': typeof DirectoryMinistriesMinistryIdRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/members/': typeof AdminMembersIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/directory/cell-groups/': typeof DirectoryCellGroupsIndexRoute
  '/directory/members/': typeof DirectoryMembersIndexRoute
  '/directory/ministries/': typeof DirectoryMinistriesIndexRoute
  '/admin/members/$memberId/edit': typeof AdminMembersMemberIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/checkin/$token'
    | '/profile/settings'
    | '/admin'
    | '/directory'
    | '/finances'
    | '/profile'
    | '/admin/attendance/$sessionId'
    | '/admin/attendance/analytics'
    | '/admin/cell-groups/$groupId'
    | '/admin/inventory/$itemId'
    | '/admin/inventory/requests'
    | '/admin/members/new'
    | '/admin/ministries/$ministryId'
    | '/directory/cell-groups/$groupId'
    | '/directory/members/$memberId'
    | '/directory/ministries/$ministryId'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/roles'
    | '/admin/users'
    | '/directory/cell-groups'
    | '/directory/members'
    | '/directory/ministries'
    | '/admin/members/$memberId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/checkin/$token'
    | '/profile/settings'
    | '/admin'
    | '/directory'
    | '/finances'
    | '/profile'
    | '/admin/attendance/$sessionId'
    | '/admin/attendance/analytics'
    | '/admin/cell-groups/$groupId'
    | '/admin/inventory/$itemId'
    | '/admin/inventory/requests'
    | '/admin/members/new'
    | '/admin/ministries/$ministryId'
    | '/directory/cell-groups/$groupId'
    | '/directory/members/$memberId'
    | '/directory/ministries/$ministryId'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/roles'
    | '/admin/users'
    | '/directory/cell-groups'
    | '/directory/members'
    | '/directory/ministries'
    | '/admin/members/$memberId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/checkin/$token'
    | '/profile/settings'
    | '/admin/'
    | '/directory/'
    | '/finances/'
    | '/profile/'
    | '/admin/attendance/$sessionId'
    | '/admin/attendance/analytics'
    | '/admin/cell-groups/$groupId'
    | '/admin/inventory/$itemId'
    | '/admin/inventory/requests'
    | '/admin/members/new'
    | '/admin/ministries/$ministryId'
    | '/directory/cell-groups/$groupId'
    | '/directory/members/$memberId'
    | '/directory/ministries/$ministryId'
    | '/admin/attendance/'
    | '/admin/members/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/directory/cell-groups/'
    | '/directory/members/'
    | '/directory/ministries/'
    | '/admin/members/$memberId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CheckinTokenRoute: typeof CheckinTokenRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  FinancesIndexRoute: typeof FinancesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  AdminAttendanceSessionIdRoute: typeof AdminAttendanceSessionIdRoute
  AdminAttendanceAnalyticsRoute: typeof AdminAttendanceAnalyticsRoute
  AdminCellGroupsGroupIdRoute: typeof AdminCellGroupsGroupIdRoute
  AdminInventoryItemIdRoute: typeof AdminInventoryItemIdRoute
  AdminInventoryRequestsRoute: typeof AdminInventoryRequestsRoute
  AdminMembersNewRoute: typeof AdminMembersNewRoute
  AdminMinistriesMinistryIdRoute: typeof AdminMinistriesMinistryIdRoute
  DirectoryCellGroupsGroupIdRoute: typeof DirectoryCellGroupsGroupIdRoute
  DirectoryMembersMemberIdRoute: typeof DirectoryMembersMemberIdRoute
  DirectoryMinistriesMinistryIdRoute: typeof DirectoryMinistriesMinistryIdRoute
  AdminAttendanceIndexRoute: typeof AdminAttendanceIndexRoute
  AdminMembersIndexRoute: typeof AdminMembersIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  DirectoryCellGroupsIndexRoute: typeof DirectoryCellGroupsIndexRoute
  DirectoryMembersIndexRoute: typeof DirectoryMembersIndexRoute
  DirectoryMinistriesIndexRoute: typeof DirectoryMinistriesIndexRoute
  AdminMembersMemberIdEditRoute: typeof AdminMembersMemberIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances/': {
      id: '/finances/'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$token': {
      id: '/checkin/$token'
      path: '/checkin/$token'
      fullPath: '/checkin/$token'
      preLoaderRoute: typeof CheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/ministries/': {
      id: '/directory/ministries/'
      path: '/directory/ministries'
      fullPath: '/directory/ministries'
      preLoaderRoute: typeof DirectoryMinistriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/members/': {
      id: '/directory/members/'
      path: '/directory/members'
      fullPath: '/directory/members'
      preLoaderRoute: typeof DirectoryMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/cell-groups/': {
      id: '/directory/cell-groups/'
      path: '/directory/cell-groups'
      fullPath: '/directory/cell-groups'
      preLoaderRoute: typeof DirectoryCellGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/': {
      id: '/admin/members/'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance/': {
      id: '/admin/attendance/'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/ministries/$ministryId': {
      id: '/directory/ministries/$ministryId'
      path: '/directory/ministries/$ministryId'
      fullPath: '/directory/ministries/$ministryId'
      preLoaderRoute: typeof DirectoryMinistriesMinistryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/members/$memberId': {
      id: '/directory/members/$memberId'
      path: '/directory/members/$memberId'
      fullPath: '/directory/members/$memberId'
      preLoaderRoute: typeof DirectoryMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/cell-groups/$groupId': {
      id: '/directory/cell-groups/$groupId'
      path: '/directory/cell-groups/$groupId'
      fullPath: '/directory/cell-groups/$groupId'
      preLoaderRoute: typeof DirectoryCellGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ministries/$ministryId': {
      id: '/admin/ministries/$ministryId'
      path: '/admin/ministries/$ministryId'
      fullPath: '/admin/ministries/$ministryId'
      preLoaderRoute: typeof AdminMinistriesMinistryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/new': {
      id: '/admin/members/new'
      path: '/admin/members/new'
      fullPath: '/admin/members/new'
      preLoaderRoute: typeof AdminMembersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory/requests': {
      id: '/admin/inventory/requests'
      path: '/admin/inventory/requests'
      fullPath: '/admin/inventory/requests'
      preLoaderRoute: typeof AdminInventoryRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory/$itemId': {
      id: '/admin/inventory/$itemId'
      path: '/admin/inventory/$itemId'
      fullPath: '/admin/inventory/$itemId'
      preLoaderRoute: typeof AdminInventoryItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cell-groups/$groupId': {
      id: '/admin/cell-groups/$groupId'
      path: '/admin/cell-groups/$groupId'
      fullPath: '/admin/cell-groups/$groupId'
      preLoaderRoute: typeof AdminCellGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance/analytics': {
      id: '/admin/attendance/analytics'
      path: '/admin/attendance/analytics'
      fullPath: '/admin/attendance/analytics'
      preLoaderRoute: typeof AdminAttendanceAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance/$sessionId': {
      id: '/admin/attendance/$sessionId'
      path: '/admin/attendance/$sessionId'
      fullPath: '/admin/attendance/$sessionId'
      preLoaderRoute: typeof AdminAttendanceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/$memberId/edit': {
      id: '/admin/members/$memberId/edit'
      path: '/admin/members/$memberId/edit'
      fullPath: '/admin/members/$memberId/edit'
      preLoaderRoute: typeof AdminMembersMemberIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CheckinTokenRoute: CheckinTokenRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  FinancesIndexRoute: FinancesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  AdminAttendanceSessionIdRoute: AdminAttendanceSessionIdRoute,
  AdminAttendanceAnalyticsRoute: AdminAttendanceAnalyticsRoute,
  AdminCellGroupsGroupIdRoute: AdminCellGroupsGroupIdRoute,
  AdminInventoryItemIdRoute: AdminInventoryItemIdRoute,
  AdminInventoryRequestsRoute: AdminInventoryRequestsRoute,
  AdminMembersNewRoute: AdminMembersNewRoute,
  AdminMinistriesMinistryIdRoute: AdminMinistriesMinistryIdRoute,
  DirectoryCellGroupsGroupIdRoute: DirectoryCellGroupsGroupIdRoute,
  DirectoryMembersMemberIdRoute: DirectoryMembersMemberIdRoute,
  DirectoryMinistriesMinistryIdRoute: DirectoryMinistriesMinistryIdRoute,
  AdminAttendanceIndexRoute: AdminAttendanceIndexRoute,
  AdminMembersIndexRoute: AdminMembersIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  DirectoryCellGroupsIndexRoute: DirectoryCellGroupsIndexRoute,
  DirectoryMembersIndexRoute: DirectoryMembersIndexRoute,
  DirectoryMinistriesIndexRoute: DirectoryMinistriesIndexRoute,
  AdminMembersMemberIdEditRoute: AdminMembersMemberIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
